import clr
import sys
sys.path.append('C:\Program Files (x86)\IronPython 2.7\Lib')
import System
from System import Array
from System.Collections.Generic import *
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference("RevitAPI")
clr.AddReference("RevitAPIUI")

import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.UI import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc = uiapp.ActiveUIDocument


flowWithUnitsList = IN[0]

#Type code bellow
flowWithoutUnitsList = []
outputList = []

for i in flowWithUnitsList[:]:
	data = i.split() #i.replace(",",".")
	flowWithoutUnitsList.append(data)

for list in flowWithoutUnitsList[:]:
	#list[0].replace(",", ".")
	del list[1]

for list in flowWithoutUnitsList[:]:
	list[0].replace(",", ".")

#Output
OUT = flowWithoutUnitsList

